ALTER TABLE users
    ADD ISDAILYDONE BOOLEAN DEFAULT FALSE;

ALTER TABLE users
    ADD ISHOURLYDONE BOOLEAN DEFAULT FALSE;

ALTER TABLE users
    ADD LEVEL INTEGER DEFAULT 1;

ALTER TABLE users
    ADD MONEY INTEGER DEFAULT 0;

ALTER TABLE users
    ADD PITY_4 INTEGER DEFAULT 0;

ALTER TABLE users
    ADD PITY_5 INTEGER DEFAULT 0;

ALTER TABLE users
    ADD PITY_6 INTEGER DEFAULT 0;

ALTER TABLE users
    ADD SECURE BOOLEAN DEFAULT FALSE;

ALTER TABLE users
    ADD SKIN_MONEY INTEGER DEFAULT 0;

ALTER TABLE users
    ADD XP INTEGER DEFAULT 0;

ALTER TABLE users
    ALTER COLUMN ISDAILYDONE SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN ISHOURLYDONE SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN LEVEL SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN MONEY SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN PITY_4 SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN PITY_5 SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN PITY_6 SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN SECURE SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN SKIN_MONEY SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN XP SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN MAIL DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN PASSWORD DROP NOT NULL;

ALTER TABLE users
DROP
COLUMN ROLE;

ALTER TABLE users
    ADD ROLE SMALLINT;

ALTER TABLE users
    ALTER COLUMN ROLE DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN USERNAME DROP NOT NULL;